labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: fffffff
    description: This will not be worked on
  - name: frontend
    color: 0e8a16
    description: Frontend related changes
  - name: backend
    color: 1d76db
    description: Backend related changes
  - name: ui/ux
    color: f9d0c4
    description: UI/UX improvements
  - name: performance
    color: 5319e7
    description: Performance improvements
  - name: security
    color: ee0701
    description: Security related changes
  - name: testing
    color: 0e8a16
    description: Testing related changes
  - name: refactor
    color: 0052cc
    description: Code refactoring
  - name: breaking
    color: ee0701
    description: Breaking changes
  - name: hotfix
    color: d93f0b
    description: Critical bug fixes 