name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '🔒 Security'
    labels:
      - 'security'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Installation

  ```bash
  npm install
  cd apps/portfolio-next
  npm run dev
  ```

  ## What's Changed

  $CHANGES

  ## Breaking Changes

  $BREAKING_CHANGES

  ## Migration Guide

  $MIGRATION_GUIDE 